### ISSUE TITLE
Dutch translation files

### ISSUE THREAD

**Issue by ghost** [tamlyn/unattach#1]
Hi there,

I've been using your plugin for quite a while now and I'd like to contribute by adding my Dutch translation files. However, I'm new to Github and have no idea how it works. So I've put the translation in a zip-file on my server for you to download: http://tinyurl.com/ngrrmv4.

I hope you can add it to the plugin. Thanks.

**Comment by tamlyn** [comment]
Thanks a lot for this! I've got your files and will add them soon.

**Comment by tamlyn** [comment]
Finally added this. Sorry for the delay.
